version: 2

# Build documentation in the docs directory with Sphinx
sphinx:
  configuration: docs/conf.py

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"
  jobs:
    post_install:
      - pip install poetry==1.3.2
      - poetry config virtualenvs.create false
      - poetry install --with doc
