version: 2

build:
  os: "ubuntu-20.04"
  tools:
    python: "mambaforge-4.10"
  jobs:
    pre_create_environment:
      - asdf plugin add poetry
      - asdf install poetry latest
      - asdf global poetry latest
      - poetry config virtualenvs.create false
    post_install:
      - poetry install -E docs

conda:
  environment: docs/conda-env.yml

# Build documentation in the doc/source directory with Sphinx
sphinx:
  configuration: docs/conf.py
