name: rtd-sphinx-build
channels:
  - conda-forge
dependencies:
  - python==3.9.*
  - python-igraph==0.9.11
  - leidenalg==0.8.10
  - pandas==1.4.*
  - spacy==3.3.*
  - spacy-model-en_core_web_sm==3.3.0
  - toolz
  - jupyter_sphinx
  - sphinx
  - pydata-sphinx-theme
  - sphinxcontrib-bibtex
