name: rtd-sphinx-build
channels:
  - conda-forge
dependencies:
  - python==3.10.*
  - python-igraph==0.10.*
  - leidenalg==0.9.*
  - pandas==1.5.*
  - spacy==3.5.*
  - spacy-model-en_core_web_sm==3.5.*
  - toolz
  - jupyter_sphinx
  - sphinx
  - pydata-sphinx-theme
  - sphinxcontrib-bibtex
